dist: trusty

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y gfortran netcdf-bin libgsl0-dev libblas-dev liblapack-dev

install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n psi4env -c psi4 --file requirements.txt python=3.6

language: cpp

script:
    # Build ndiff tool
    - cd $TRAVIS_BUILD_DIR/codes/ndiff-2.00; ./configure; make
    - PATH=$TRAVIS_BUILD_DIR/codes/ndiff-2.00:$PATH

    - cd $TRAVIS_BUILD_DIR; source install.sh

    # test the python package
    - cd $TRAVIS_BUILD_DIR; python run_tests.py

    # polynomial tests
    - cd $TRAVIS_BUILD_DIR/oldtests/polytests/1B; bash run_test.sh
    #- cd $TRAVIS_BUILD_DIR/polynomial_generation/tests/2B; bash run_test.sh
    #- cd $TRAVIS_BUILD_DIR/polynomial_generation/tests/3B; bash run_test.sh

    - cd $TRAVIS_BUILD_DIR/oldtests/polytests/input_generation; bash run_test.sh

    # requires MKL, cannot run on Travis-CI unless we reconfigure it to use conda
    #- cd $TRAVIS_BUILD_DIR/fitting/1B/get_codes; bash run_test.sh

    # psi4
    - cd $TRAVIS_BUILD_DIR/oldtests/calctests/psi4; source activate psi4env; bash run_test.sh

    # QM MB energy calculator (uses psi4)
    - cd $TRAVIS_BUILD_DIR/oldtests/calctests/monomer; source activate psi4env; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/oldtests/calctests/monomers; source activate psi4env; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/oldtests/calctests/dimer; source activate psi4env; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/oldtests/calctests/dimers; source activate psi4env; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/oldtests/calctests/trimer; source activate psi4env; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/oldtests/calctests/trimers; source activate psi4env; bash run_test.sh

    # training set generation
    - cd $TRAVIS_BUILD_DIR/codes/normal_distribution_configs; make
    - cd $TRAVIS_BUILD_DIR/oldtests/norm_dist/scripts; bash run_test.sh
    #- cd $TRAVIS_BUILD_DIR/configuration_generator/norm_distribution/scripts; bash run_test_so4.sh
    #- cd $TRAVIS_BUILD_DIR/configuration_generator/norm_distribution/scripts; bash run_test_pf6.sh
    #- cd $TRAVIS_BUILD_DIR/configuration_generator/norm_distribution/scripts; bash run_test_trimer_minimum.sh
    #- cd $TRAVIS_BUILD_DIR/configuration_generator/norm_distribution/scripts; bash run_test_trimer_saddle.sh
    - cd $TRAVIS_BUILD_DIR/oldtests/configtests; bash run_test.sh
