dist: trusty

language: bash

before_install:
    - sudo apt-get update
    - sudo apt-get install libgsl0ldbl
    - sudo apt-get install libnetcdf-dev

script:
    - cd $TRAVIS_BUILD_DIR/polynomial_generation/tests/1B; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/polynomial_generation/tests/2B; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/polynomial_generation/tests/3B; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/polynomial_generation/tests/input_generation; bash run_test.sh
    - cd $TRAVIS_BUILD_DIR/fitting/1B/get_codes ; bash run_test.sh
